import type { BuildingMaster, InventoryItem } from "./types";

export const MIN_SCALE = 0.5;
export const MAX_SCALE = 2.5;
export const ZOOM_STEP = 0.15;
export const STORE_ANIMATION_MS = 260;

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    type: "tent",
    name: "TENT",
    title: "旅人のテント",
    description: "ギルドの仲間が遠征前に集う簡易拠点。休息と作戦会議に使われる。",
    count: 2,
    src: "/town/tent.png",
    minMapWidth: 210,
    mapWidthVw: 29,
    maxMapWidth: 430,
  },
  {
    type: "bonfire",
    name: "BONFIRE",
    title: "団らんの焚き火",
    description: "夜のギルドタウンを照らす小さな火。仲間の士気をじんわり温める。",
    count: 3,
    src: "/town/bonfire.png",
    minMapWidth: 92,
    mapWidthVw: 12,
    maxMapWidth: 164,
  },
];

export const BUILDING_MASTERS: BuildingMaster[] = [
  {
    id: "plasma-condenser",
    name: "プラズマ・コンデンサ",
    description: "ログイン時の継続的なCP供給を支えるギルドタウンの基礎電源。",
    previewSrc: "/build-items/plasma-capacitor.jpeg",
    requiredGuildLevel: 1,
    buffType: "daily",
    targetSpLanguage: "Common",
    levels: [
      { level: 1, upgradeCostCp: 120, upgradeCostSp: 0, buffValue: 50 },
      { level: 2, upgradeCostCp: 250, upgradeCostSp: 0, buffValue: 80 },
      { level: 3, upgradeCostCp: 600, upgradeCostSp: 0, buffValue: 120 },
      { level: 4, upgradeCostCp: 1500, upgradeCostSp: 0, buffValue: 180 },
      { level: 5, upgradeCostCp: 3500, upgradeCostSp: 0, buffValue: 250 },
    ],
  },
  {
    id: "hacker-hideout",
    name: "ハッカーの隠れ家",
    description: "深夜帯の集中作業から得られるCPを強化する秘密拠点。",
    previewSrc: "/build-items/Hacker_s_Lean-to.png",
    requiredGuildLevel: 1,
    buffType: "night",
    targetSpLanguage: "Common",
    levels: [
      { level: 1, upgradeCostCp: 160, upgradeCostSp: 20, buffValue: 0.15 },
      { level: 2, upgradeCostCp: 400, upgradeCostSp: 60, buffValue: 0.2 },
      { level: 3, upgradeCostCp: 1000, upgradeCostSp: 160, buffValue: 0.28 },
      { level: 4, upgradeCostCp: 2600, upgradeCostSp: 400, buffValue: 0.38 },
      { level: 5, upgradeCostCp: 6000, upgradeCostSp: 1000, buffValue: 0.5 },
    ],
  },
  {
    id: "llm-semantic-compiler",
    name: "LLM・セマンティック解析コンパイラ",
    description: "コードから得られる全言語のSP（Skill Point）獲得効率を底上げするアレイ。",
    previewSrc: "/build-items/llm-semantic-compiler-removebg.png",
    requiredGuildLevel: 1,
    buffType: "spBoost",
    targetSpLanguage: "Common",
    levels: [
      { level: 1, upgradeCostCp: 200, upgradeCostSp: 20, buffValue: 0.15 },
      { level: 2, upgradeCostCp: 480, upgradeCostSp: 80, buffValue: 0.25 },
      { level: 3, upgradeCostCp: 1200, upgradeCostSp: 200, buffValue: 0.4 },
      { level: 4, upgradeCostCp: 3200, upgradeCostSp: 480, buffValue: 0.6 },
      { level: 5, upgradeCostCp: 8000, upgradeCostSp: 1400, buffValue: 0.9 },
    ],
  },
  {
    id: "ai-pair-programming-pod",
    name: "AIペアプログラミング・ポッド",
    description: "コミット由来のCPを大きく伸ばすTypeScript特化の開発支援設備。",
    previewSrc: "/build-items/AI_Pair_Programming_Pod.png",
    requiredGuildLevel: 2,
    buffType: "commit",
    targetSpLanguage: "TypeScript",
    levels: [
      { level: 1, upgradeCostCp: 240, upgradeCostSp: 60, buffValue: 0.2 },
      { level: 2, upgradeCostCp: 600, upgradeCostSp: 160, buffValue: 0.32 },
      { level: 3, upgradeCostCp: 1600, upgradeCostSp: 400, buffValue: 0.48 },
      { level: 4, upgradeCostCp: 4000, upgradeCostSp: 1100, buffValue: 0.68 },
      { level: 5, upgradeCostCp: 8000, upgradeCostSp: 2800, buffValue: 0.9 },
    ],
  },
  {
    id: "refactoring-lab",
    name: "リファクタリング・ラボ",
    description: "将来のレビューイベント拡張に備えた品質改善特化の研究施設。",
    previewSrc: "/build-items/Refactoring_Lab.png",
    requiredGuildLevel: 2,
    buffType: "refactor",
    targetSpLanguage: "TypeScript",
    levels: [
      { level: 1, upgradeCostCp: 280, upgradeCostSp: 80, buffValue: 0.25 },
      { level: 2, upgradeCostCp: 720, upgradeCostSp: 200, buffValue: 0.38 },
      { level: 3, upgradeCostCp: 1800, upgradeCostSp: 520, buffValue: 0.55 },
      { level: 4, upgradeCostCp: 4800, upgradeCostSp: 1400, buffValue: 0.75 },
      { level: 5, upgradeCostCp: 10000, upgradeCostSp: 3400, buffValue: 1 },
    ],
  },
  {
    id: "algorithm-arena",
    name: "アルゴリズム闘技場",
    description: "将来の学習課題検知に備え、精進由来のCPを強化する演習場。",
    previewSrc: "/build-items/Algorithm_Arena.png",
    requiredGuildLevel: 3,
    buffType: "arena",
    targetSpLanguage: "Go",
    levels: [
      { level: 1, upgradeCostCp: 320, upgradeCostSp: 100, buffValue: 0.3 },
      { level: 2, upgradeCostCp: 800, upgradeCostSp: 260, buffValue: 0.45 },
      { level: 3, upgradeCostCp: 2200, upgradeCostSp: 720, buffValue: 0.65 },
      { level: 4, upgradeCostCp: 6000, upgradeCostSp: 1800, buffValue: 0.9 },
      { level: 5, upgradeCostCp: 12000, upgradeCostSp: 4000, buffValue: 1.2 },
    ],
  },
  {
    id: "distributed-data-bank",
    name: "分散型データバンク",
    description: "未消費CPにデイリー利息を発生させる分散管理型の保管庫。",
    previewSrc: "/build-items/Distributed_Data_Bank.png",
    requiredGuildLevel: 3,
    buffType: "interest",
    targetSpLanguage: "Go",
    levels: [
      { level: 1, upgradeCostCp: 400, upgradeCostSp: 120, buffValue: 0.001 },
      { level: 2, upgradeCostCp: 1000, upgradeCostSp: 320, buffValue: 0.0018 },
      { level: 3, upgradeCostCp: 2800, upgradeCostSp: 880, buffValue: 0.0028 },
      { level: 4, upgradeCostCp: 7200, upgradeCostSp: 2200, buffValue: 0.0038 },
      { level: 5, upgradeCostCp: 14000, upgradeCostSp: 4800, buffValue: 0.005 },
    ],
  },
  {
    id: "ci-cd-automation-plant",
    name: "CI/CD自動化プラント",
    description: "建築に必要なCPコストを圧縮するRust特化の自動化工場。",
    previewSrc: "/build-items/CI_CD_Automation_Plant.png",
    requiredGuildLevel: 4,
    buffType: "plant",
    targetSpLanguage: "Rust",
    levels: [
      { level: 1, upgradeCostCp: 600, upgradeCostSp: 200, buffValue: 0.1 },
      { level: 2, upgradeCostCp: 1400, upgradeCostSp: 480, buffValue: 0.14 },
      { level: 3, upgradeCostCp: 3600, upgradeCostSp: 1200, buffValue: 0.19 },
      { level: 4, upgradeCostCp: 8800, upgradeCostSp: 3000, buffValue: 0.24 },
      { level: 5, upgradeCostCp: 18000, upgradeCostSp: 7200, buffValue: 0.3 },
    ],
  },
  {
    id: "concurrency-tower",
    name: "並行処理タワー",
    description: "同日中の連続コミットに対するコンボCPを高めるGo特化タワー。",
    previewSrc: "/build-items/Concurrency_Tower.png",
    requiredGuildLevel: 4,
    buffType: "tower",
    targetSpLanguage: "Go",
    levels: [
      { level: 1, upgradeCostCp: 800, upgradeCostSp: 240, buffValue: 0.5 },
      { level: 2, upgradeCostCp: 1800, upgradeCostSp: 600, buffValue: 0.7 },
      { level: 3, upgradeCostCp: 4400, upgradeCostSp: 1600, buffValue: 0.95 },
      { level: 4, upgradeCostCp: 10400, upgradeCostSp: 3600, buffValue: 1.2 },
      { level: 5, upgradeCostCp: 20000, upgradeCostSp: 8000, buffValue: 1.5 },
    ],
  },
  {
    id: "cyber-data-core",
    name: "サイバー・データコア",
    description: "ギルド全員の基本CPを底上げする最上位の共有中枢。",
    previewSrc: "/build-items/Cyber_Data_Core.png",
    requiredGuildLevel: 5,
    buffType: "core",
    targetSpLanguage: "Common",
    levels: [
      { level: 1, upgradeCostCp: 1500, upgradeCostSp: 600, buffValue: 0.1 },
      { level: 2, upgradeCostCp: 3600, upgradeCostSp: 1500, buffValue: 0.15 },
      { level: 3, upgradeCostCp: 7500, upgradeCostSp: 3000, buffValue: 0.21 },
      { level: 4, upgradeCostCp: 12000, upgradeCostSp: 5400, buffValue: 0.28 },
      { level: 5, upgradeCostCp: 18000, upgradeCostSp: 7500, buffValue: 0.35 },
    ],
  },
];
