export const PATHS = {
  ROOT: "/",
  PROFILE: "/profile",
  ANALYSIS: "/analysis",
  HOME: "/home",
  MY_PAGE: "/mypage",
  PETS: "/pets",
  BATTLE: "/battle",
  GUILD: "/guild",
  GUILD_SELECT: "/guild/select",
  GUILD_DETAILS: "/guild/details",
  GUILD_MY_GUILD: "/guild/my-guild",
  GUILD_TOWN: "/guild/town",
  GUILD_TECH_NEWS: "/guild/news",
  WAR: "/war",
} as const;
